### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'emit')

### ISSUE THREAD

**Issue by madjed-hue** [google-map-react/google-map-react#1116]
Uncaught TypeError: Cannot read properties of undefined (reading 'emit')
    at r._onMapMouseMove (google_map.js:970:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4161:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4210:1)
    at invokeGuardedCallback (react-dom.development.js:4274:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4288:1)
    at executeDispatch (react-dom.development.js:9038:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9070:1)
    at processDispatchQueue (react-dom.development.js:9083:1)
    at dispatchEventsForPlugins (react-dom.development.js:9094:1)
    at react-dom.development.js:9285:1

**Environment:**

 - OS: [windows]
 - Browser [chrome]

**Comment by AtaydeEnrique** [comment]
I had the same issue, try removing <React.StrictMode></React.StrictMode> from your index.js file

**Comment by Mateusz-Podemski-Forte-Digital** [comment]
Do you know how to fix it without removing strict mode?

**Comment by TrevorDecker** [comment]
I am receiving this with React.StrictMode removed.  It only shows up for me when I run with nextjs in development mode and only started showing up when I upgraded to react 18

**Comment by Ash-Layek** [comment]
@Mateusz-Podemski-Forte-Digital  did you figure it out ? I have the same problem and i'm looking for a way to fix it without disabling strict mode

**Comment by Mateusz-Podemski-Forte-Digital** [comment]
Unfortunately no, for local development I had to disable strict mode :/

**Comment by armedi** [comment]
I fixed this issue by using the old `ReactDOM.render(...)` instead of `ReactDOM.createRoot(...).render(...)`
