### ISSUE TITLE
FitBounds not working

### ISSUE THREAD

**Issue by PrateekGoyal18** [google-map-react/google-map-react#1147]
Hi All,

I am trying to use fitBounds function example from here - https://github.com/google-map-react/google-map-react/blob/master/API.md#fitbounds-func, but I am getting this error whenever I am calling it
```
Uncaught _.oe {message: 'not a LatLngBounds or LatLngBoundsLiteral: unknown property ne', stack: 'Error\n    
at _.oe.captureStackTrace (https://maps.…maps-api-v3/api/js/50/7a/intl/en_gb/map.js:65:267', name: 'InvalidValueError'}
```

My code is something like this - 

```
const GoogleMap = ({ isLoading, markersData}) => {
  const [boundsFitted, setBoundsFitted] = useState(false)
  
  const apiIsLoaded = (map, maps) => {
    if (!boundsFitted) {
      const bounds = {
        ne: {
          lat: 50,
          lng: -118,
        },
        sw: {
          lat: 32,
          lng: -92,
        },
      }
      const size = {
        width: 640,
        height: 400,
      }
      const { center, zoom } = map.fitBounds(bounds, size)
      console.log('center and zoom', center, zoom)
      setBoundsFitted(true)
    }
  }

  return (
      <Box sx={{ width: 640, height: 400 }} >
        {isLoading ? (
          <Skeleton width={'100%'} height={'100%'} />
        ) : (
          <GoogleMapReact
            key={new Date().getTime()}
            bootstrapURLKeys={{
              key: GOOGLE_MAPS_API_KEY,
              libraries: ['places', 'geometry', 'drawing', 'visualization'],
            }}
            options={mapOptions}
            defaultCenter={MAP_DEFAULT_PROPS.center}
            defaultZoom={MAP_DEFAULT_PROPS.zoom}
            yesIWantToUseGoogleMapApiInternals
            onGoogleApiLoaded={({ map, maps }) => apiIsLoaded(map, maps)}
          >
            {!isLoading &&
              markersData.length > 0 &&
              markersData.map((marker) => (
                <Marker
                  key={marker.facilityIdentifer}
                  lat={Number(marker.latitude)}
                  lng={Number(marker.longitude)}
                  data={marker}
                />
              ))}
          </GoogleMapReact>
        )}
      </Box>
  )
}

```

**Comment by giorgiabosello** [comment]
You are declaring bounds wrongly. This is an example of bounds created with `google.maps.LatLngBounds()`:
```json
{
    "south": 1.4620887,
    "west": -117.636948,
    "north": 59.4432756,
    "east": 116.1489727
}
```

```javascript
let bounds = new window.google.maps.LatLngBounds()
bounds.extend(new window.google.maps.LatLngBounds(lat, lng))
map.fitBounds(bounds)
```

**Comment by PrateekGoyal18** [comment]
@giorgiabosello I am still getting this error when using your solution - 
```
Uncaught _.oe {message: 'not a LatLng or LatLngLiteral: not an Object', stack: 'Error\n    
at _.oe.captureStackTrace (https://maps.…maps-api-v3/api/js/50/7a/intl/en_gb/map.js:65:181', name: 'InvalidValueError'}
```

**Comment by giorgiabosello** [comment]
@PrateekGoyal18 kike this?
```javascript
let bounds = new window.google.maps.LatLngBounds()
bounds.extend(new window.google.maps.LatLngBounds(bounds.ne.lat, bounds.ne.lng))
bounds.extend(new window.google.maps.LatLngBounds(bounds.sw.lat, bounds.sw.lng))
map.fitBounds(bounds)
```

**Comment by PrateekGoyal18** [comment]
@giorgiabosello but how to insert custom latitude and longitude in above code as its just extending current bounds object?

**Comment by giorgiabosello** [comment]
@PrateekGoyal18 sorry, bounds inside the function are referring to yours.
```javascript
const boundsObj = {
    ne: {
        lat: 50,
        lng: -118,
    },
    sw: {
        lat: 32,
        ng: -92,
    },
 }
let bounds = new window.google.maps.LatLngBounds()
bounds.extend(new window.google.maps.LatLngBounds(boundsObj.sw.lat, boundsObj.sw.lng))
bounds.extend(new window.google.maps.LatLngBounds(boundsObj.ne.lat, boundsObj.ne.lng))
map.fitBounds(bounds)
```

**Comment by PrateekGoyal18** [comment]
@giorgiabosello is it possible to connect with you sometime over a meet call maybe, becauuse I am still facing some issues with the solution ?

**Comment by giorgiabosello** [comment]
@PrateekGoyal18 I can help you with a codesandbox, if you create one.

**Comment by PrateekGoyal18** [comment]
@giorgiabosello ya thats a good suggestion, give me some time and I'll share that link with you

**Comment by PrateekGoyal18** [comment]
@giorgiabosello here is the codesandbox link - https://codesandbox.io/s/google-maps-test-fwwvs9?file=/src/GoogleMap.js
If you zoom out the map, you will see there are many other markers all over the world, and their data usually comes from api, so we need to set the bounds in a manner that in 1 snapshot a user can see all specified markers (wherever they may be situated)

**Comment by giorgiabosello** [comment]
@PrateekGoyal18 you have markers with wrong latitude or longitude coordinates.
See this: https://codesandbox.io/s/google-maps-test-forked-4xmgfh?file=/src/GoogleMap.js

**Comment by PrateekGoyal18** [comment]
@giorgiabosello your solution worked like a charm.
Thanks a lot for all your help!

**Comment by amilkarferra** [comment]
please [giorgiabosello](https://github.com/giorgiabosello) can you provide us the code again?? the sandbox in your link does'nt exist any more.. THANKS
