### ISSUE TITLE
Warning: Invalid DOM property `color-interpolation-filters`. Did you mean `colorInterpolationFilters`?

### ISSUE THREAD

**Issue by carlosLMZarego** [google-map-react/google-map-react#1184]
Hello, I'm trying to use this package in my nextjs app v13.1.1, I follow the guide but the map is not been displayed and I'm not sure if it could be by these two warnings

```
next-dev.js?3515:20 
        
       Warning: Invalid DOM property `color-interpolation-filters`. Did you mean `colorInterpolationFilters`?
    at filter
    at defs
    at svg
    at MarkMap
    at div
    at div
    at o (webpack-internal:///./node_modules/google-map-react/dist/index.modern.js:22:1947)
    at div
    at C
    at div
    at o (webpack-internal:///./node_modules/google-map-react/dist/index.modern.js:22:17541)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at CardContent (webpack-internal:///./node_modules/@mui/material/CardContent/CardContent.js:48:82)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Paper (webpack-internal:///./node_modules/@mui/material/Paper/Paper.js:77:83)
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Card (webpack-internal:///./node_modules/@mui/material/Card/Card.js:49:82)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Grid (webpack-internal:///./node_modules/@mui/material/Grid/Grid.js:390:87)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Grid (webpack-internal:///./node_modules/@mui/material/Grid/Grid.js:390:87)
    at CgServices (webpack-internal:///./src/custom_components/cgDetails/views/cgServices.tsx:111:24)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at TabPanel (webpack-internal:///./node_modules/@mui/lab/TabPanel/TabPanel.js:45:84)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Box (webpack-internal:///./node_modules/@mui/system/esm/createBox.js:34:72)
    at TabContext (webpack-internal:///./node_modules/@mui/lab/TabContext/TabContext.js:34:5)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Grid (webpack-internal:///./node_modules/@mui/material/Grid/Grid.js:390:87)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Grid (webpack-internal:///./node_modules/@mui/material/Grid/Grid.js:390:87)
    at CgDetails (webpack-internal:///./src/custom_components/cgDetails/cgDetails.tsx:85:13)
    at div
    at CaregiverDetailPage (webpack-internal:///./src/pages/caregivers/[id]/tab/[tab].tsx:23:78)
    at main
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Box (webpack-internal:///./node_modules/@mui/system/esm/createBox.js:34:72)
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at VerticalLayout (webpack-internal:///./src/@core/layouts/VerticalLayout.tsx:65:13)
    at Layout (webpack-internal:///./src/@core/layouts/Layout.tsx:18:13)
    at UserLayout (webpack-internal:///./src/layouts/UserLayout.tsx:30:11)
    at InnerThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:21:70)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/private-theming/ThemeProvider/ThemeProvider.js:43:5)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:40:5)
    at CustomThemeProvider (webpack-internal:///./src/hooks/customThemeProvider.tsx:9:22)
    at AclGuard (webpack-internal:///./src/@core/components/auth/AclGuard.tsx:31:13)
    at AuthGuard (webpack-internal:///./src/@core/components/auth/AuthGuard.tsx:19:13)
    at Guard (webpack-internal:///./src/pages/_app.tsx:103:11)
    at WindowWrapper (webpack-internal:///./src/@core/components/window-wrapper/index.tsx:15:11)
    at Direction (webpack-internal:///./src/layouts/components/Direction.tsx:27:13)
    at InnerThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:21:70)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/private-theming/ThemeProvider/ThemeProvider.js:43:5)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:40:5)
    at ThemeComponent (webpack-internal:///./src/@core/theme/ThemeComponent.tsx:36:13)
    at SettingsProvider (webpack-internal:///./src/@core/context/settingsContext.tsx:76:11)
    at AuthProvider (webpack-internal:///./src/context/AuthContext.tsx:39:11)
    at Provider (webpack-internal:///./node_modules/react-redux/es/components/Provider.js:13:3)
    at App (webpack-internal:///./src/pages/_app.tsx:131:13)
    at PathnameContextProviderAdapter (webpack-internal:///./node_modules/next/dist/shared/lib/router/adapters.js:62:11)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:301:63)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:850:919)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:61:1)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:171:11)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:346:11)
```

```
Warning: Invalid DOM property `stroke-width`. Did you mean `strokeWidth`?
    at path
    at g
    at svg
    at MarkMap
    at div
    at div
    at o (webpack-internal:///./node_modules/google-map-react/dist/index.modern.js:22:1947)
    at div
    at C
    at div
    at o (webpack-internal:///./node_modules/google-map-react/dist/index.modern.js:22:17541)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at CardContent (webpack-internal:///./node_modules/@mui/material/CardContent/CardContent.js:48:82)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Paper (webpack-internal:///./node_modules/@mui/material/Paper/Paper.js:77:83)
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Card (webpack-internal:///./node_modules/@mui/material/Card/Card.js:49:82)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Grid (webpack-internal:///./node_modules/@mui/material/Grid/Grid.js:390:87)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Grid (webpack-internal:///./node_modules/@mui/material/Grid/Grid.js:390:87)
    at CgServices (webpack-internal:///./src/custom_components/cgDetails/views/cgServices.tsx:111:24)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at TabPanel (webpack-internal:///./node_modules/@mui/lab/TabPanel/TabPanel.js:45:84)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Box (webpack-internal:///./node_modules/@mui/system/esm/createBox.js:34:72)
    at TabContext (webpack-internal:///./node_modules/@mui/lab/TabContext/TabContext.js:34:5)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Grid (webpack-internal:///./node_modules/@mui/material/Grid/Grid.js:390:87)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Grid (webpack-internal:///./node_modules/@mui/material/Grid/Grid.js:390:87)
    at CgDetails (webpack-internal:///./src/custom_components/cgDetails/cgDetails.tsx:85:13)
    at div
    at CaregiverDetailPage (webpack-internal:///./src/pages/caregivers/[id]/tab/[tab].tsx:23:78)
    at main
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Box (webpack-internal:///./node_modules/@mui/system/esm/createBox.js:34:72)
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at VerticalLayout (webpack-internal:///./src/@core/layouts/VerticalLayout.tsx:65:13)
    at Layout (webpack-internal:///./src/@core/layouts/Layout.tsx:18:13)
    at UserLayout (webpack-internal:///./src/layouts/UserLayout.tsx:30:11)
    at InnerThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:21:70)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/private-theming/ThemeProvider/ThemeProvider.js:43:5)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:40:5)
    at CustomThemeProvider (webpack-internal:///./src/hooks/customThemeProvider.tsx:9:22)
    at AclGuard (webpack-internal:///./src/@core/components/auth/AclGuard.tsx:31:13)
    at AuthGuard (webpack-internal:///./src/@core/components/auth/AuthGuard.tsx:19:13)
    at Guard (webpack-internal:///./src/pages/_app.tsx:103:11)
    at WindowWrapper (webpack-internal:///./src/@core/components/window-wrapper/index.tsx:15:11)
    at Direction (webpack-internal:///./src/layouts/components/Direction.tsx:27:13)
    at InnerThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:21:70)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/private-theming/ThemeProvider/ThemeProvider.js:43:5)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:40:5)
    at ThemeComponent (webpack-internal:///./src/@core/theme/ThemeComponent.tsx:36:13)
    at SettingsProvider (webpack-internal:///./src/@core/context/settingsContext.tsx:76:11)
    at AuthProvider (webpack-internal:///./src/context/AuthContext.tsx:39:11)
    at Provider (webpack-internal:///./node_modules/react-redux/es/components/Provider.js:13:3)
    at App (webpack-internal:///./src/pages/_app.tsx:131:13)
    at PathnameContextProviderAdapter (webpack-internal:///./node_modules/next/dist/shared/lib/router/adapters.js:62:11)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:301:63)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:850:919)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:61:1)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:171:11)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:346:11)

```

I'm not receiving any other error....how can I fix this? thank you

**Comment by carlosLMZarego** [comment]
ok, after set strict mode to false the warnings stopped but the map is still not showing
