### ISSUE TITLE
Cannot read property 'animationName' of undefined

### ISSUE THREAD

**Issue by arherzf8er** [google-map-react/google-map-react#695]
Great component, love its functionality so far!
But since v.1.1.1 this error appears sometimes, can't locate the problem:

### Cannot read property 'animationName' of undefined
```
TypeError: Cannot read property 'animationName' of undefined
    at Object.<anonymous> (/home/user/app/node_modules/google-map-react/lib/utils/detectElementResize.js:96:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/app/node_modules/google-map-react/lib/google_map.js:87:28)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/app/node_modules/google-map-react/lib/index.js:6:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by itsmichaeldiego** [comment]
@arherzf8er mmm that is weird, we did not move much things in 1.1.1 related to animation. When does it happen exactly?

**Comment by arherzf8er** [comment]
@itsmichaeldiego yep, I installed it on that app around August I suppose and haven't updated it since, so what version was it at that time? Maybe it might help. Also I can't blame the syntax I used or anything related, since it just worked and I haven't touched it after setting up. But I do updated React to the latest version along with this component. 

Could you please point me where I even can start tackling with debugging?
